name = "KeqCraft"
author = "KeqCraft Team"
version = "26.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f156aad1b44d5799bc87547798bff5c047cba5b3b2e602ecc1c0710f7d5668c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21.1"]
