name = "KeqCraft"
author = "KeqCraft Team"
version = "26.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d265921f30565963f4a40fbe4621df2bcbcc9b29c42be086e6476622b9489de"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21.1"]
