name = "KeqCraft"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45f0313c7b334ae824cbe4b379cd50944a4c03c0e6e6345111ddfef22b790912"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.187"
