name = "KeqCraft"
author = "KeqCraft Team"
version = "26.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a690d38529aac1b7532c2e514201595d851c69d79691da285f7e69af7ed27d7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.21.1"]
