ServerEvents.recipes(event =>{

	event.recipes.create.mixing('minecraft:gunpowder', '16x minecraft:flint')
	event.recipes.create.deploying('pointblank:gunmetal_ingot', ['minecraft:iron_ingot', 'minecraft:copper_ingot'])
	event.recipes.create.compacting('pointblank:ammo9mm', ['minecraft:copper_ingot', 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo45acp', ['minecraft:copper_ingot', 'create:copper_nugget', 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo46', ['minecraft:copper_ingot', '2x create:copper_nugget', 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo357', ['minecraft:copper_ingot', '4x create:copper_nugget', 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo57', ['minecraft:copper_ingot', '3x create:copper_nugget', 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo50ae', ['minecraft:copper_ingot', '2x minecraft:iron_nugget', 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo545', ['2x minecraft:copper_ingot', 'create:copper_nugget', 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo556', ['2x minecraft:copper_ingot', '2x create:copper_nugget', 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo68', ['2x minecraft:copper_ingot', '3x create:copper_nugget', 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo762', ['2x minecraft:copper_ingot', '2x minecraft:iron_nugget', 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo762x51', ['3x minecraft:copper_ingot', '4x minecraft:iron_nugget' 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo338lapua', ['3x minecraft:copper_ingot', '5x minecraft:iron_nugget' '2x minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo50bmg', ['4x minecraft:copper_ingot', 'minecraft:iron_ingot', '3x minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammo12gauge', ['9x create:copper_nugget', 'minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:ammolasercharge', ['2x minecraft:copper_ingot', 'minecraft:iron_ingot', '3x minecraft:redstone'])
	event.recipes.create.compacting('pointblank:grenade40mm', ['1x minecraft:copper_ingot', 'minecraft:iron_ingot', 'minecraft:tnt'])
	event.recipes.create.compacting('pointblank:grenade20mm', ['1x minecraft:copper_ingot', 'minecraft:iron_ingot', '3x minecraft:gunpowder'])
	event.recipes.create.compacting('pointblank:smaw_rocket', ['10x pointblank:gunmetal_ingot', 'create:copper_nugget', 'minecraft:tnt'])
	event.recipes.create.compacting('pointblank:at4_rocket', ['10x pointblank:gunmetal_ingot', 'minecraft:iron_ingot', 'minecraft:tnt'])
	event.recipes.create.compacting('pointblank:javelin_rocket', ['10x pointblank:gunmetal_ingot', 'pointblank:processor', '33x minecraft:redstone', 'minecraft:tnt'])

})